//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class BetHistory
    {
        public int History_id { get; set; }
        public Nullable<int> Bet_id { get; set; }
        public Nullable<decimal> Old_amount { get; set; }
        public Nullable<decimal> New_amount { get; set; }
        public Nullable<System.DateTime> Change_date { get; set; }
    }
}
