//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Participants
    {
        public int Participant_id { get; set; }
        public Nullable<int> Race_id { get; set; }
        public Nullable<int> Horse_id { get; set; }
        public string Jockey_name { get; set; }
    
        public virtual Horses Horses { get; set; }
        public virtual Races Races { get; set; }
    }
}
